[package]
name = "quickmark-cli"
version = "1.1.0"
edition = "2021"
description = "Lightning-fast Markdown/CommonMark linter CLI tool with tree-sitter based parsing"
license = "MIT"
authors = ["Evgeny Kropotin"]
repository = "https://github.com/ekropotin/quickmark"
homepage = "https://github.com/ekropotin/quickmark"
keywords = ["markdown", "linter", "lint", "cli"]
categories = ["command-line-utilities", "text-processing", "development-tools"]

[[bin]]
name = "qmark"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive"] }
quickmark-core = { path = "../quickmark-core", version = "1.1.0" }
glob = "0.3"
rayon = "1.12"
ignore = "0.4"
walkdir = "2.5"

[dev-dependencies.quickmark-core]
path = "../quickmark-core"
version = "1.1.0"
features = ["testing"]

[dev-dependencies]
assert_cmd = "2.2"
assert_fs = "1.1"
predicates = "3.1"
